spring:
  application:
    name:
      weatherScheduler
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weather
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/weather
    user: postgres
    password: postgres
    baseline-on-migrate: true

logging:
  level:
    org.springframework: INFO
    sql: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG

open-weather:
  url: ${WEATHER_ROOT_URL:404}
  api-key: ${WEATHER_API_KEY:404}